Bilder fuer neue Handzeichen
Die-KoMa/neulingsheft pull request #6
Opened 2019-11-08 13:54 UTC by 24auhsoj

Wie im AK Meta in Potsdam besprochen hier die neuen Handzeichen als Bilder. Wer auch immer den Text zum "Du fällst aus dem Rahmen" machen wollte, sollte das noch tun.

2019-11-08 16:11 UTC, mmarx requested changes

2019-11-08 16:11 UTC, mmarx commented on handzeichen.tex
> +\end{itemize}
Da ist, glaube ich, der Kontext etwas verloren gegangen.

2019-11-08 17:05 UTC, 24auhsoj commented on handzeichen.tex
> +\end{itemize}
An der Stelle wollte jemand anderes noch einen Text zu schreiben - da ich das nicht bin, der Blindtext.

2019-11-11 14:38 UTC, mmarx commented on handzeichen.tex
> +\end{itemize}
Okay, dann bitte entweder noch den Text direkt hier im PR unterbringen, oder einen separaten PR, der auf diesem aufbaut, damit dann beides gleichzeitig gemerged werden kann.

2023-05-20 17:21 UTC, mgkurtz commented
Hinfällig durch 5792b06.

2023-05-20 17:21 UTC, closed without merging